default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: around_development

test:
  <<: *default
  database: around_test

production:
  <<: *default
  url: "postgres://around:Arnon007@localhost/around_production"
